package org.purnamaproject.xui.impl;

/**
 * @(#)XUIOpenFileDialogImpl.java   0.5 18/08/2003
 *
 * The Purnama Project XUI (XML-based User Interface) API is an set of program
 * calls that utilize the XUI tagset and perform the task of creating a user
 * interface. The Purnama version of this API is specific using Java as the platform
 * but other XUI APIs may use other libraries and platforms. The Purnama XUI API
 * supports the creation of Swing components, adding, deleting and laying out
 * components. It also supports dynamic binding of business logic to the user
 * interface.
 *
 * Copyright (c) 2003 Arron Ferguson
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * For more information, please contact Arron Ferguson at:
 * e-mail: arron_ferguson@bcit.ca
 * snail-mail: SW2 - 124, 3700 Willingdon Avenue, Burnaby, British Columbia, Canada, V5G 3H2
 * Web: http://xml.bcit.ca/PurnamaProject/
 *
 */

import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.Toolkit;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Hashtable;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFileChooser;
import org.purnamaproject.xui.helpers.IDFactory;
import org.purnamaproject.xui.helpers.XUIFilter;
import org.purnamaproject.xui.binding.XUIModel;
import org.purnamaproject.xui.binding.ActionModel;
import org.purnamaproject.xui.component.container.toplevel.XUIOpenFileDialog;
import org.purnamaproject.xui.component.container.toplevel.XUIWindow;
import org.purnamaproject.xui.impl.XUINodeImpl;
import org.purnamaproject.xui.XUIDisplayException;
import org.purnamaproject.xui.component.XUIComponent;
import org.purnamaproject.xui.XUINode;
import org.purnamaproject.xui.GridMapping;
import org.purnamaproject.xui.XUITypeFormatException;

/**
 * The implementation of a XUI OpenFileDialog. allows the user to graphically select and
 * open a file from a list presented. If any listeners are registered with this component
 * they will be given a reference to the file.
 *
 * @version 0.5 18/08/2003
 * @author  Arron Ferguson
 */
public class XUIOpenFileDialogImpl implements XUIOpenFileDialog, ActionListener
{
    /**
     * List of supported components that can be placed inside of this one.
     */
    private static LinkedList supportedComponents = null;

    static
    {
        supportedComponents = new LinkedList();
        supportedComponents.add("No supported types for OpenFileDialog.");
    }

    /**
     * Value to determine whether or not this component should be displayed when visualize is called.
     */
    private boolean windowVisibility = false;

    /**
     * Node associated with this component.
     */
    private XUINode dialogNode = null;

    /**
     * The native peer representing the XUI file dialog component.
     */
    private JFileChooser dialog = null;

    /**
     * The grid width of this component (in grid cells).
     */
    private int gridWidth = 2;

    /**
     * The grid height of this component (in grid cells).
     */
    private int gridHeight = 1;

    /**
     * The grid x coordinate of this component (within the grid).
     */
    private int gridX = 1;

    /**
     * The grid y coordinate of this component (within the grid).
     */
    private int gridY = 1;

    /**
     * The list of filters that are accepted (viewable) within the file dialog.
     */
    private XUIFilter filters;

    /**
     * The parent window that owns this dialog.
     */
    private XUIWindow window;

    /**
     * The list of model objects that are ready to be listeners to any events generated by this
     * component.
     */
    private List actionModelList = new java.util.LinkedList();

    /**
     * <p>Constructs a new XUIBasicDialog implementation and passing it its XML node rather
     * than requiring the XUIBasicDialog implementation to build it from scratch. This
     * method is called by the Realizer when it reads the XML document from the file
     * system.</p>
     *
     * <p><b><u>Note:</u></b> This constructor is not normally something that should be called up.
     * This constructor is required when creating a XUI File dialog where the node has already been built
     * by the realizer or a subclass thereof.</p>
     *
     * <p><b><u>Note:</u></b> Schema checking is assumed at this point. Any node passed to this method
     * will be assumed to have passed through the schema validator.</p>
     *
     * @see #setComponentSize(int, int)
     * @see #setComponentLocation(int, int)
     * @throws org.purnamaproject.xui.XUIDisplayException if the component is being placed overtop of an existing component on the
     * layout.
     * @param node the new node representing this GUI component.
     */
    public XUIOpenFileDialogImpl(XUINode node) throws XUIDisplayException
    {
        int x = Integer.parseInt(node.getAttributeValue("x"));
        int y = Integer.parseInt(node.getAttributeValue("y"));
        int width = Integer.parseInt(node.getAttributeValue("width"));
        int height = Integer.parseInt(node.getAttributeValue("height"));

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        if(!(node.getName().equals("OpenFileDialog")))
            throw new XUIDisplayException("Node for XUIOpenFileDialog must be named 'OpenFileDialog' and conform to the XUI schema.");
        else if(x > (d.getWidth() + width) || x < (0 - width))
            throw new XUIDisplayException("x and y values must fall within the desktop's resolution.");
        else if(y > (d.getHeight() + height) || y < (0 - height))
            throw new XUIDisplayException("x and y values must fall within the desktop's resolution.");
        else
        {

            dialogNode = node;
            dialogNode.setXUIComponent(this);
            dialog = new JFileChooser(System.getProperty("user.dir"));
            window = (XUIWindow)dialogNode.getParent().getXUIComponent();
            filters = new XUIFilter();
            // need to instantiate the peer first
            windowVisibility = Boolean.valueOf(node.getAttributeValue("visible")).booleanValue();

            // get filters
            List filterList = dialogNode.getChildNodesByName("Filter");
            for(int f = 0; f < filterList.size(); f++)
            {
                XUINode filter = (XUINode)filterList.get(f);
                filters.addType(filter.getCDATA());
            }
            // add them to the chooser
            dialog.addChoosableFileFilter(filters);


            dialog.setSize(width, height);
            dialog.setLocation(x, y);

            // keep track of window positioning
            dialog.addComponentListener(new ComponentAdapter()
                {
                    /**
                     * Update XUI node to reflect the move.
                     */
                    public void componentMoved(ComponentEvent e)
                    {
                        Component c = e.getComponent();
                        setComponentLocation(c.getX(), c.getY());
                    }

                    /**
                     * Update XUI node to reflect the resize.
                     */
                    public void componentResized(ComponentEvent e)
                    {
                        Component c = e.getComponent();
                        setComponentSize(c.getWidth(), c.getHeight());
                    }
            });

        }
    }

    /**
     * Default constructor that creates a file dialog at the top of the screen with the dimensions
     * 300 x 150 and as an open file dialog box with no filtering of file extensions. If calling this
     * method, a call to setParentWindow is required.
     */
    public XUIOpenFileDialogImpl()
    {

        // now create the XML version of this element
        dialogNode = new XUINodeImpl("OpenFileDialog");
        dialogNode.setLevel(2);
        dialogNode.addNamespace("xui", "http://xml.bcit.ca/PurnamaProject/2003/xui");
        dialogNode.setXUIComponent(this);

        // add window specific attributes
        dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "id", "id", "xs:ID",
            IDFactory.getInstance().generateID("openfiledialog"));
        dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "x", "x", "xs:unsignedShort",
            "1");
        dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "y", "y", "xs:unsignedShort",
            "1");
        dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "width", "width", "xs:unsignedShort",
            "300");
        dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "height", "height", "xs:unsignedShort",
            "150");
        dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "visible", "visible", "xs:boolean",
            "false");

    }

    /**
     * Creates a file dialog component that accepts the parent window that this dialog belongs to.
     *
     * @param parent the parent window that this dialog belongs to.
     */
    public XUIOpenFileDialogImpl(XUIWindow parent, String name) throws XUIDisplayException
    {
        this();
        if(name == null)
            throw new XUIDisplayException("message must not be null.");
        if(parent == null)
            throw new XUIDisplayException("parent must not be null.");

        window = parent;

        dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "name", "name", "xs:string",
        name);
        dialog.setName(name);

    }

    /**
     * Sets the parent of this file dialog.
     *
     * @param parent the parent window of this file dialog.
     */
    public void setParentWindow(XUIWindow parent)
    {
        window = parent;
    }

    /**
     * <p>Sets the component's XML element's visible attribute. This does not actually make the component visible.
     * In order to see the component visible, call the <code>visualize()</code> method.</p>
     *
     * @param visibility true means this component is visible and false means it is not.
     * @see #visualize()
     */
    public void setVisible(boolean visibility)
    {
        dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "visible", "visible", "xs:boolean",
            "" + visibility);
        windowVisibility = visibility;
        this.visualize();
    }

    /**
     * If this component has its visible attribute set to true, the component will then be visualized (i.e.
     * displayed on the screen).
     */
    public void visualize()
    {
        dialog.setSize(Integer.parseInt(dialogNode.getAttributeValue("width")),
            Integer.parseInt(dialogNode.getAttributeValue("height")));
        dialog.setLocation(Integer.parseInt(dialogNode.getAttributeValue("x")),
            Integer.parseInt(dialogNode.getAttributeValue("y")));
        if(Boolean.valueOf(dialogNode.getAttributeValue("visible")).booleanValue())
            dialog.showOpenDialog(window.getPeer());

    }

    /**
     * Returns whether this component is visible or not.
     *
     * @return visible state (true or false).
     */
    public boolean isVisible()
    {
        return windowVisibility;
    }

    /**
     * Returns the XUI id reference of this component.
     *
     * @return the id reference of this component as a string.
     * @see #setIDRef(String)
     */
    public String getIDRef()
    {
        return dialogNode.getAttributeValue("idref");
    }

    /**
     * Sets the XUI id reference of this component. This value is a reference to parent container that
     * this component is a child of. The string values allowed can contain both alphabetic and numeric
     * characters. The first character must start with an alphabetic character. Real-time validation
     * is performed and therefor if a wrong value is entered, an exception is generated.
     *
     * @see <a href="http://www.w3c.org/TR/xmlschema-2/#IDREF">W3C XML Schema, section 3.3.9</a>
     * @throws org.purnamaproject.xui.XUITypeFormatException if the type does not conform to the W3C XML Schema IDREF
     * type, or if the string is null, an exception occurs.
     * @param newIDRef the new ID reference value to assign to this component.
     */
    public void setIDRef(String newIDRef) throws XUITypeFormatException
    {
        if(!(IDFactory.getInstance().containsID(newIDRef)))
            throw new XUITypeFormatException("The ID reference must reference an existing ID.");
        if(newIDRef.matches("[^a-zA-Z]"))
            dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "idref", "idref", "xs:IDREF",
                newIDRef);
        else
            throw new XUITypeFormatException("ID reference must start with alphabetic only: a - z or A - Z.");
    }

    /**
     * Returns the selected file as a file object.
     *
     * @return the selected file.
     */
    public File getSelectedFile()
    {
        return dialog.getSelectedFile();
    }

    /**
     * Returns the selected file as a URL. Returns null if there is an error with the File
     * being converted to a URL.
     *
     * @return the selected file as a URL.
     */
    public URL getSelectedFileAsURL()
    {
        try
        {
            return dialog.getSelectedFile().toURL();
        }catch(MalformedURLException mue)
        {
            return null;
        }
    }

    /**
     * Returns the filters used within the file dialog.
     *
     * @return a list of strings that represent the filters used with this file dialog.
     * @see #addFilter(String)
     */
    public List getFilters()
    {
        return filters.getTypes();
    }

    /**
     * Removes the filters from this file dialog. If no filters are found, no action is taken.
     *
     * @see #addFilter(String)
     */
    public void removeAllFilters()
    {
        filters.removeAllTypes();
    }

    /**
     * Adds a list of new filters to this file dialog box. Filters allow the user to choose from a list of known
     * file types which makes looking for a particular file more efficient. The types of values that are allowed
     * are any character using either numerics or alphabetic characters (both upper and lower case). There must be
     * at least 1 character, but no more than 4 characters. Real-time validation is performed and therefor if a
     * wrong value is entered, an exception is generated.
     *
     * @see <a href="http://www.w3c.org/TR/xmlschema-2/#token">W3C XML Schema, section 3.3.2</a>
     * @see <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>
     * @throws org.purnamaproject.xui.XUITypeFormatException if the type does not conform to the W3C XML Schema token
     * type, or if the string is null, an exception occurs.
     * @param newFilters     a new filter to add to this file dialog box.
     */
    public void addFilters(List newFilters) throws XUITypeFormatException
    {
        if(newFilters == null)
            throw new XUITypeFormatException("list cannot be null.");
        for(int n = 0; n < newFilters.size(); n++)
        {
            String ext = (String)newFilters.get(n);
            if(!(ext.matches("[a-zA-Z0-9]{1,4}+")))
                throw new XUITypeFormatException("Filter type: > 0 && < 5, using letters a-z, A-Z, 0-9.");
        }
        filters.addTypes(newFilters);
    }

    /**
     * Adds a new filter to this file dialog box. Filters allow the user to choose from a list of known file types
     * which makes looking for a particular file more efficient. The types of values that are allowed are any
     * character using either numerics or alphabetic characters (both upper and lower case). There must be at
     * least 1 character, but no more than 4 characters. Real-time validation is performed and therefor if a
     * wrong value is entered, an exception is generated.
     *
     * @see <a href="http://www.w3c.org/TR/xmlschema-2/#token">W3C XML Schema, section 3.3.2</a>
     * @see <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>
     * @throws org.purnamaproject.xui.XUITypeFormatException if the type does not conform to the W3C XML Schema token
     * type, or if the string is null, an exception occurs.
     * @param newFilter a new filter to add to this file dialog box.
     */
    public void addFilter(String newFilter) throws XUITypeFormatException
    {
        if(newFilter == null)
            throw new XUITypeFormatException("string value cannot be null.");
        else if(!(newFilter.matches("[a-zA-Z0-9]{1,4}+")))
            throw new XUITypeFormatException("Filter type: > 0 && < 5, using letters a-z, A-Z, 0-9.");
        else
            filters.addType(newFilter);
    }

    /**
     * Returns the x coordinate of this component. For a top level container, this coordinate is the actual
     * x coordinate value (in pixels) that appears on the desktop. For an intermediate component, this x
     * coordinate is the position within the layout grid that is assigned to the top level container.
     *
     * @return the x coordinate of this component.
     */
    public int getX()
    {
        return gridX;
    }

    /**
     * Returns the y coordinate of this component. For a top level container, this coordinate is the actual
     * y coordinate value (in pixels) that appears on the desktop. For an intermediate component, this y
     * coordinate is the position within the layout grid that is assigned to the top level container.
     *
     * @return the y coordinate of this component.
     */
    public int getY()
    {
        return gridY;
    }

    /**
     * Returns the width of this component. For a top level container, this value is the actual width
     * (in pixels) that appears on the desktop. For an intermediate component, this width value is the
     * position within the layout grid that is assigned to the top level container (e.g. 2 would be two
     * cells wide.
     *
     * @return the width of this component.
     */
    public int getWidth()
    {
        return gridWidth;
    }

    /**
     * Returns the height of this component. For a top level container, this value is the actual height
     * (in pixels) that appears on the desktop. For an intermediate component, this height value is the
     * position within the layout grid that is assigned to the top level container (e.g. 2 would be two
     * cells high.
     *
     * @return the height of this component.
     */
    public int getHeight()
    {
        return gridHeight;
    }

    /**
     * Returns the XUI id of this component.
     *
     * @return the id of this component as a string.

     */
    public String getID()
    {
        return dialogNode.getAttributeValue("id");
    }

    /**
     * Represents the XUI window component as a XUI node.
     *
     * @return org.purnamaproject.xui.XUINode the XML element as a XUI node.
     */
    public XUINode getNodeRepresentation()
    {
        return dialogNode;
    }

    /**
     * <p>This method returns the peer within the host operating system and user interface environment.
     * For each environment, this will return a different object type and may not be represented as
     * a class called component.</p>
     *
     * <p><b>This component does not return anything </b></p>
     *
     * @return Component which is the native representation of the GUI component.

     */
    public Component getPeer()
    {
        return null;
    }

    /**
     * <p>Sets the location of this component using x and y coordinates. This value will be different for top-level
     * containers as compared to intermediate level containers and atomic and composite components. For example,
     * for intermediate level containers, atomic components and composite components, the x and y coordinate
     * is the position within the layout grid. The x and y values must fall within the XUI schema limits
     * (0 to 65,655) as well as within the limits of the layout.</p>
     *
     * <p>If the integer number does not fall within the number 0 to 65,535, then a <code>XUIDisplayException</code>
     * is thrown and no change is made. If the integer number falls within this schema limit but outside of the
     * range of the grid, (i.e. grid is 5 x 5 but the value given starts at coordinate 8), then no update to the
     * layout is made (i.e. the component is not added to the layout.)</p>
     *
     * <p>If the coordinate values fall within the xml schema limits and falls within the grid range but another
     * component is currently inhabiting that area on the grid, then a <code>XUIDisplayException</code> is
     * thrown and no change is made (i.e. the component is not added to the layout.)</p>
     *
     * <p>If the component is a top-level container, then the x and y coordinate values refer to the screen
     * coordinates on the screen. The same rules apply to adhering to the integer range constraint. If the
     * top-level container is placed outside of the screen resolution of the host system, then a
     * <code>XUIDisplayException</code> is thrown and no change is made.</p>
     *
     * <p><b>For FileDialog, this method sets the component on the screen. The top level components
     * have the difference that their x and y coordinates are screen coordinates and not grid coordinates.
     * For this reason, their type for x and y are slightly different than that of an intermediate component,
     * composite component or an atomic component. A top level container has a signed short instead of an
     * unsigned short. Thus the value for the integer can be from -32,768 to 32,767 instead of from
     * 0 to 65,535.</b></p>
     *
     * @see <a href="http://www.w3c.org/TR/xmlschema-2/#unsignedShort">W3C XML Schema, section 3.3.23</a>
     * @see <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>
     * @throws org.purnamaproject.xui.XUIDisplayException if the component is being placed overtop of an existing component on the
     * layout.
     * @param yCoordinate the y coordinate.
     * @param xCoordinate the x coordinate.
     */
    public void setComponentLocation(int xCoordinate, int yCoordinate) throws XUIDisplayException
    {
        if(xCoordinate < -32768 || xCoordinate > 32767)
            throw new XUIDisplayException("x and y values must be within the range of 0 - 65535.");
        if(yCoordinate < -32768 || yCoordinate > 32767)
            throw new XUIDisplayException("x and y values must be within the range of 0 - 65535.");
        else
        {
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            if(xCoordinate > (d.getWidth() + dialog.getWidth()) || xCoordinate < (0 - dialog.getWidth()))
                throw new XUIDisplayException("x and y values must fall within the desktop's resolution.");
            else if(yCoordinate > (d.getHeight() + dialog.getHeight()) || yCoordinate < (0 - dialog.getHeight()))
                throw new XUIDisplayException("x and y values must fall within the desktop's resolution.");
            else
            {
                dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "x", "x", "xs:unsignedShort",
                    String.valueOf(xCoordinate));
                dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "y", "y", "xs:unsignedShort",
                    String.valueOf(yCoordinate));
                dialog.setLocation(xCoordinate, yCoordinate);
            }
        }
    }

    /**
     * <p>Sets the size of this component using width and height integers. This value will be different for top-level
     * containers as compared to intermediate level containers and atomic and composite components. For example,
     * for intermediate level containers, atomic components and composite components, the width and height integers
     * are the size in cells within the layout grid. The width and height values must fall within the XUI schema
     * limits (0 to 65,655) as well as within the limits of the layout.</p>
     *
     * <p>If the integer number does not fall within the number 0 to 65,535, then a <code>XUIDisplayException</code>
     * is thrown and no change is made. If the integer number falls within this schema limit but outside of the
     * range of the grid, (i.e. grid is 5 x 5 but the value given for width is 8), then no update to the
     * layout is made (i.e. the component is not added to the layout.)</p>
     *
     * <p>If the dimension values falls within the xml schema limits and falls within the grid range but another
     * component is currently inhabiting that area on the grid, then a <code>XUIDisplayException</code> is
     * thrown and no change is made (i.e. the component is not added to the layout.)</p>
     *
     * <p>If the component is a top-level container, then the width and height values refer to the size in pixels
     * instead of grid cells. The same rules apply to adhering to the integer range constraint. If the
     * top-level container is wider or taller than the screen resolution of the host system, then a
     * <code>XUIDisplayException</code> is thrown and no change is made.</p>
     *
     * <p><b>For FileDialog, this method sets the component on the screen. The top level components
     * have the difference that their width and their height are screen values and not grid values.
     * For this reason, their type for width and height are slightly different than that of an intermediate component,
     * composite component or an atomic component. A top level container has a signed short instead of an
     * unsigned short. Thus the value for the integer can be from -32,768 to 32,767 instead of from
     * 0 to 65,535.</b></p>
     *
     * @see <a href="http://www.w3c.org/TR/xmlschema-2/#unsignedShort">W3C XML Schema, section 3.3.23</a>
     * @see <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>
     * @throws org.purnamaproject.xui.XUIDisplayException if the component is being placed overtop of an existing component on the
     * layout.
     * @param width the width of the component.
     * @param height the height of the component.
     */
    public void setComponentSize(int width, int height) throws XUIDisplayException
    {
        if(width < -32768 || width > 32767)
            throw new XUIDisplayException("width and height values must be within the range of 0 - 65535.");
        if(height < -32768 || height > 32767)
            throw new XUIDisplayException("width and height values must be within the range of 0 - 65535.");
        else
        {
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            if(width > 32767)
                throw new XUIDisplayException("x and y values must fall within the desktop's resolution.");
            else if(height > 32767)
                throw new XUIDisplayException("x and y values must fall within the desktop's resolution.");
            else
            {
                dialog.setSize(width, height);
                dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "width", "width", "xs:unsignedShort",
                    String.valueOf(width));
                dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "height", "height", "xs:unsignedShort",
                    String.valueOf(height));
            }
        }
    }

    /**
     * <p>Adds a new component to this container. The type of component must adhere to the XUI specification.
     * Real-time validation is performed and therefor if the wrong type of component is added, an exception
     * is generated. For each type of container (each concrete class), there will be a listed set of
     * components supported by that particular container.</p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     *
     * @see <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>
     * @see #getSupportedComponents()
     * @throws org.purnamaproject.xui.XUITypeFormatException if the type does not conform to the
     * <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>.
     * @param component the component to add.    */
    public void addComponent(XUIComponent component) throws XUITypeFormatException
    {
        ; // nada
    }

    /**
     * <p>Removes all of the components from this container. If no components found then this method
     * does nothing.</p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     */
    public void removeAllComponents()
    {
        ; // nada
    }

    /**
     * <p>Removes the component based on its object reference. If no component found by that reference,
     * no action is taken.</p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     *
     * @param component the component to remove.
     */
    public void removeComponent(XUIComponent component)
    {
        ; // nada
    }

    /**
     * <p>Removes the component based on its id. If no component found by that id, no action is taken.</p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     *
     * @param id the id of the component to remove.
     */
    public void removeComponent(String id)
    {
        ; // nada
    }

    /**
     * Returns the XUI name of this component as a string.
     *
     * @return the name of this component.
     * @see #setName(String)
     */
    public String getName()
    {
        return dialogNode.getAttributeValue("name");
    }

    /**
     * Sets the XUI name of this component. The string values allowed can contain
     * both alphabetic and numerica characters. Real-time validation is performed and
     * therefor if a wrong value is entered, an exception is generated.
     *
     * @see <a href="http://www.w3c.org/TR/xmlschema-2/#string">W3C XML Schema, section 3.2.1</a>
     * @see <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>
     * @throws org.purnamaproject.xui.XUITypeFormatException if the type does not conform to the W3C XML Schema string
     * type, or if the string is null, an exception occurs.
     * @param newName the new name to assign to this component.
     */
    public void setName(String newName) throws XUITypeFormatException
    {
        if(newName == null)
            throw new XUITypeFormatException("Panel name cannot be a null string.");
        else
        {
            dialogNode.addAttribute("http://xml.bcit.ca/PurnamaProject/2003/xui", "name", "name", "xs:string",
            newName);
        }
    }

    /**
     * <p>Gets the component based on its id. If no component found by that id, null is returned.</p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     *
     * @param id the id of the component to get. Component remains.
     */
    public XUIComponent getComponent(String id)
    {
        return null;
    }

    /**
     * <p>Gets all the components in this container. If no components found, null is returned.</p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     *
     * @return a list of the components that are currently children of this container.
     */
    public List getChildrenComponents()
    {
        return null;
    }

    /**
     * This method returns a list of strings. Each string is a fully qualified name of the components that
     * are supported. Supported means that the component can be added to this component. It is an error to add
     * a component that is not supported. An exception is generated.
     *
     * @see <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>
     * @return a list of Strings where each string is the fully qualified name of each component supported.
     */
    public List getSupportedComponents()
    {
        return supportedComponents;
    }

    /**
     * <p>Sets the grid (rows x columns) of this component. The value allowed for this must fall within the
     * range from 0 to 65,535. Real-time validation is performed and therefor if a wrong value is entered,
     * an exception is generated. If this method is not called or any constructors provided that allow the
     * grid to be set, a default grid size of 5 x 5 will be given.</p>
     *
     * @see <a href="http://www.w3c.org/TR/xmlschema-2/#unsignedShort">W3C XML Schema, section 3.3.23</a>
     * @see <a href="http://geekkit.bcit.ca/xui/docs/specification/xuiSpecification0.5.0.html">Purnama Project XUI Specification</a>
     * @throws org.purnamaproject.xui.XUIDisplayException if the type does not conform to the W3C XML Schema unsignedshort type.
     * @param rows the number of rows within the grid.
     * @param columns the number of columns within the grid.
     */
    public void setGrid(int rows, int columns) throws XUIDisplayException
    {
        ; // nada
    }

    /**
     * <p>Returns the grid height and width.</p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     *
     * @return the grid height and width as a <code>java.awt.Dimension</code> object.
     */
    public Dimension getGrid()
    {
        return null;
    }

    /**
     * <p>Returns a hashtable which contains XUIComponents as keys and rectangles as the regions
     * occupied on the grid by child components. Used for components to determine if they are
     * attempting to take up space on the container where another component already exists.</p>
     *
     * <p><b>For XUIBasicDialog this method does not perform any task. It is required because this component
     * is an intermediate container.</b></p>
     *
     * @return the hashtable of the components and their mapped rectangle regions.
     */
    public Hashtable getGridMapping()
    {
        return null;
    }

    /**
     * Handles an action event from the underlying GUI peer.
     *
     * @param e the <code>ActionEvent</code>.
     */
    public void actionPerformed(ActionEvent e)
    {
        if(e.getSource() == dialog)
        {
            int size = actionModelList.size();
            for(int i = 0; i < size; i++)
            {
                ActionModel model = (ActionModel)actionModelList.get(i);
                model.action(this);
            }

        }
    }

    /**
     * Adds a new model to listen to the <code>XUIComponent</code> that also is a <code>XUIEventSource</code>.
     * If the model is not an instance of the ActionModel type, then no binding is done.
     *
     * @param model the model that listens to events based on this type.
     */
    public void addEventListener(XUIModel model)
    {
        if(model instanceof ActionModel)
        {
            // call up the action model.
            actionModelList.add(model);
            dialog.addActionListener(this);
        }
    }

    /**
     * Delete a model from the <code>XUIComponent</code> that also is a <code>XUIEventSource</code>.
     *
     * @param model the model that is to no longer be a listener.
     */
    public void removeEventListener(XUIModel model)
    {
        actionModelList.remove(model);
        dialog.removeActionListener(this);
    }
}
